### ISSUE TITLE
Text color in menubar while it is selected is too dark

### ISSUE THREAD

**Issue by imranmunshi** [B00merang-Project/Windows-10-Dark#1]
When in a gtk3 application I select a menu item from the menu bar of say LIbreoffice, the text of the menu labels, during the selection, becomes too dark to be sufficiently visible.
![2017-06-05-14 06 38-screen](https://cloud.githubusercontent.com/assets/5736192/26776835/8b963f8c-49f8-11e7-90e7-dc2b03c81016.png)

**Comment by Elbullazul** [comment]
@imranmunshi will check the bug

**Comment by Elbullazul** [comment]
not relevant anymore
