### ISSUE TITLE
Renaming foreground still visible

### ISSUE THREAD

**Issue by leogx9r** [B00merang-Project/Windows-10-Dark#11]
On the latest version, when renaming items in Cinnamon, the old name of them item is still shown and overlaps with the new name.

Unfortunately I couldn't actually capture it properly but I hope the following attached images show what I mean.

![image](https://user-images.githubusercontent.com/40126089/55285439-e33cb480-537b-11e9-8d94-527aaf647bba.png)

![image](https://user-images.githubusercontent.com/40126089/55285442-ed5eb300-537b-11e9-9656-48e2cc38e423.png)

**Comment by leogx9r** [comment]
@Elbullazul any progress on this by chance? This is my daily driver theme and it's pretty much the only imperfection I can find with this.

**Comment by Elbullazul** [comment]
sorry, was very busy. Probably will check it this sunday

which version of cinnamon do you use?

also, it's the default file manager (nemo), yes?

**Comment by leogx9r** [comment]
@Elbullazul Sorry for the late response, been busy myself. I'm using the latest Cinnamon version (`v4.0.10` ) but this issue should present itself with at least all versions of Cinnamon since 4.0.

For nemo, I'm using version, `v4.0.6` which is also the latest public release.

![image](https://user-images.githubusercontent.com/40126089/58065972-111dc880-7b77-11e9-8e88-5ddb57bdf762.png)
![image](https://user-images.githubusercontent.com/40126089/58065945-f6e3ea80-7b76-11e9-82fd-416948c2fb17.png)

**Comment by Elbullazul** [comment]
I found what causes the bug but haven't patched it yet, will probably publish a bit later today

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Project/Windows-10-Dark/commit/24860ae2767cd6ded219dbaa93ffed67b05cf31b possibly fixes this, I haven't had time to test it

**Comment by leogx9r** [comment]
Yep, I can confirm that commit 24860ae has fixed it. Thanks a lot.

Also confirmed the issue is also present for Windows-10-Acrylic-Dark, Windows-10-Acrylic and Windows-10 themes (possibly others as well) but since this issue was solved for this particular project, I'll close this issue.
