### ISSUE TITLE
Panel - selected tab/window

### ISSUE THREAD

**Issue by truefriend-cz** [B00merang-Project/Windows-10-Dark#12]
Hi. Please add to Panel color for active tabs/window.
Windows have color mouseover effect (gray up) and selected window color grayed upper.
Now is is grayed text only on selected Window/tab on panel. No selected Windows is text color white. And selected Window have text color grayed.
Thanks

**Comment by Elbullazul** [comment]
Hello,

Can you post images of what you want and how it looks currently?

Thanks

**Comment by truefriend-cz** [comment]
Ok. This is Linux panel (Theme Windows-10-Dark on Linux Xubuntu 19.04 - xfce version):
https://imgur.com/a/ZRcfgDw
(active open Window is Skype, mouseover is on Folder (Temp - Správce souborů) and Chrome is on background)

and this is Windows panel.
https://imgur.com/a/HiuUPWP
(active open Window is Skype, mouseover is on Folder (GitHub - Požadavky) and Chrome is on background)

I want on Linux panel same as Windows.
I understand it's hard work, but it is enough if the text stays white color and the selected (open) window is gray color. If you could also activate partially gray when you swipe over the mouse it would also be great.

**Comment by Elbullazul** [comment]
780fdb6b fixes this

**Comment by truefriend-cz** [comment]
Thanks. It's much better. I would like to fine-tune it a bit and then make the source code available here. I programer a little. Can you recommend or advise me on a need for a terminal command that can restore the theme of the appearance? To apply changes immediately.

**Comment by Elbullazul** [comment]
You can fork the repo, do the changes and submit a pull request with github after pushing to github
