### ISSUE TITLE
Recomended mouse cursor pack

### ISSUE THREAD

**Issue by truefriend-cz** [B00merang-Project/Windows-10-Dark#13]
Hi. What would you recommend with a Windows mouse cursor package for this theme?
Thanks

**Comment by dominichayesferen** [comment]
A Windows 8 cursor theme, because the cursors weren't changed from Windows 8's.

**Comment by Elbullazul** [comment]
I remember using one of these: https://www.opendesktop.org/search/projectSearchText/win8/page/1/pci/107

probably this one: https://www.opendesktop.org/p/999870/

**Comment by ojvribeiro** [comment]
This one is the best I found: https://github.com/birbkeks/windows-cursors

![Image](https://github.com/user-attachments/assets/cc56ed41-f4e8-42a6-806f-afb1b9a8ae05)
