### ISSUE TITLE
Black texts

### ISSUE THREAD

**Issue by truefriend-cz** [B00merang-Project/Windows-10-Dark#14]
Hi. I have problem on Linux Mint 19.1 XFCE.
All texts on panels and desktop is black. (i wanted white, or settings from the OS).
https://imgur.com/a/M25Taui

**Comment by Elbullazul** [comment]
I'm a bit busy ATM, but will view this as soon as I can, thanks for the feedback

**Comment by Elbullazul** [comment]
it appears to have been fixed sometime in the last month

**Comment by truefriend-cz** [comment]
No. I tested now. This problem stayed.
I can try to solve the problem myself. Just write me what configuration file it is (and in what folder) and the line number that should handle it. I program CSS for sites so it should be similar. If I can fix it, I'll send a solution here.

**Comment by Elbullazul** [comment]
![VirtualBox_Linux Mint 19 1 Xfce_10_06_2019_19_35_28](https://user-images.githubusercontent.com/15310985/59233550-f3141880-8bb6-11e9-902a-a43815fffb65.png)

fixed

thought it was GTK3 related but it ended up being a color in gtkrc (GTK 2)
