### ISSUE TITLE
Black texts continue from... (it appears to have been fixed sometime in the last month)

### ISSUE THREAD

**Issue by truefriend-cz** [B00merang-Project/Windows-10-Dark#15]
it appears to have been fixed sometime in the last month

_Originally posted by @Elbullazul in https://github.com/B00merang-Project/Windows-10-Dark/issues/14#issuecomment-500059056_

No. I tested now. This problem stayed.
I can try to solve the problem myself. Just write me what configuration file it is (and in what folder) and the line number that should handle it. I program CSS for sites so it should be similar. If I can fix it, I'll send a solution here.

**Comment by Elbullazul** [comment]
gonna reopen the other one, updates in short

**Comment by truefriend-cz** [comment]
Yes, thanks. Perfect fix. Works ok!
