### ISSUE TITLE
mismatch panel color and xfwm4 menu bar

### ISSUE THREAD

**Issue by denikris** [B00merang-Project/Windows-10-Dark#16]
xubuntu 19.04 with xfce 4.13.x

there are some mismatch color in xfce panel 4.13.x
xfce4-places-plugin and xfce4-dockbarx-plugin have darker color than other panel items
and there is some apps that have menu bar with different color to xfwm4 window title
![windows10darkpanel](https://user-images.githubusercontent.com/16707606/60515219-5c460200-9d05-11e9-91b9-40fd45a168e1.png)

**Comment by Elbullazul** [comment]
got it. can't test it right now but I should push a fix tomorow or this afternoon (7 PM EST)

**Comment by Elbullazul** [comment]
does https://github.com/B00merang-Project/Windows-10-Dark/archive/master.zip fix this issue?

**Comment by denikris** [comment]
panel and its components are fix now, but xfwm4 window title and menubar still mismatch

![windows10darkpanel](https://user-images.githubusercontent.com/16707606/60666823-35690680-9e92-11e9-8b82-121ca22846c8.png)

**Comment by denikris** [comment]
also for the older version of xfce panel (4.12.2 on xubuntu18.04) still have problem with transparency
![windows10darkpanel](https://user-images.githubusercontent.com/16707606/60666996-a14b6f00-9e92-11e9-8eb6-419b8d7a20f1.png)

**Comment by Elbullazul** [comment]
@denikris for the last one you used xfce's built-in transparency setting for the panel?

**Comment by denikris** [comment]
yes, in 4.12.x it can be set with 'none (use system style)' and 'solid color' and my screenshot is using system style with alpha 0
in 4.13.x work (no issue) because panel this version can only set transparency with 'solid color'

**Comment by Elbullazul** [comment]
the Xfce panel uses a mix of GTK2 and GTK3 controls, which can cause issues since they work differently and I'm not even shure GTK2 supports transparency.

I'll give it a look but I don't think I can do much for that

**Comment by Elbullazul** [comment]
I'm of two minds with this. Some apps (mainly those with menubars) will look better, but some other ones are currently matching and will have the same color difference.

I'm going to leave it like this, but depending on what comes next (possible all-black menubar as in Windows Explorer), I might reopen this issue
