### ISSUE TITLE
Lots of xsession errors in latest version.

### ISSUE THREAD

**Issue by frankzen** [B00merang-Project/Windows-10-Dark#19]
DL the latest (July) version of dark variant this morning and my .xsession-errors file is filling up with errors like:

(mate-appearance-properties:1989): Gtk-WARNING **: 11:20:01.475: Theme parsing error: gtk.css:166:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(mate-appearance-properties:1989): Gtk-WARNING **: 11:20:01.475: Theme parsing error: gtk.css:187:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(engrampa:1999): Gtk-WARNING **: 11:20:16.961: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(engrampa:1999): Gtk-WARNING **: 11:20:16.961: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

 I know I could do a search/replace operation but I know little or nothing about css and worry about causing major problems.

**Comment by Elbullazul** [comment]
I don't think it's related to this particular theme. I just checked the release and couldn't find an :insensitive occurrence. I deprecated that pseudo-class a while back. I never used :inconsistant either.

maybe check what lightDM theme you have?

Just giving some CSS info here in case it helps. pseudo-classes are status indicators of a widget (object), ex. hover in this case was :prelight.

if the parser complains it still understands the rule. If there was something like unknown pseudo-class, then you would have to replace it, but gnome still processes old pseudo-classes for the moment.

**Comment by frankzen** [comment]
Strange. This is the result of grep in the ~/.themes/Windows-10 directory
[list.txt](https://github.com/B00merang-Project/Windows-10-Dark/files/3731269/list.txt)

**Comment by Elbullazul** [comment]
can you run the same with `:` before the pseudo-class?

**Comment by frankzen** [comment]
grep -ri :insensitive *


[list.txt](https://github.com/B00merang-Project/Windows-10-Dark/files/3734393/list.txt)

**Comment by Elbullazul** [comment]
couldn't find any reference to those pseudo-classes in GTK 3.20 source files. check your lightDM theme or the default mate theme

since it's not related, I'm going to close the issue, but can still help you if you want to fix those warnings

**Comment by frankzen** [comment]
Discovered this morning there was a gtk.css file in ~/.config/gtk-3.0 that was the source of most of the errors I was getting in the .xsessions-errors file. I wonder why it's there but obviously many gtk2.0 and gtk 3.0 programs read it.
