### ISSUE TITLE
Controls missing in HiDPI

### ISSUE THREAD

**Issue by libexpand** [B00merang-Project/Windows-10-Dark#22]
When the screen is scaled due to a high resolution and HiDPI is enabled, the controls are missing everywhere (the check box's and radio buttons).

OS: Kali MATE
Resolution: 3840 x 2400
HiDPI enabled

Using GTK.

Missing checkbox's
![Screenshot at 2020-04-13 11-31-29](https://user-images.githubusercontent.com/50190252/79085472-06b28180-7d7c-11ea-81de-42769592dd7d.png)

It should look like this (using another theme):
![Screenshot at 2020-04-13 11-29-31](https://user-images.githubusercontent.com/50190252/79085302-68262080-7d7b-11ea-9ade-c9b0f01ccd7f.png)

**Comment by Elbullazul** [comment]
if you launch the app from the terminal do you get any warnings?

**Comment by libexpand** [comment]
Ran `mate-tweak`, no errors via terminal.
Ran `mate-appearance-properties`, no errors via terminal.
Let me know how else I can assist.

**Comment by Elbullazul** [comment]
where are the themes installed?

**Comment by libexpand** [comment]
```
~/.themes/Windows-10
~/.themes/Windows-10-Dark
```

- Permission's on folder: `drwxr-xr-x`
- Standard user with `sudo`

**Comment by Elbullazul** [comment]
confirmed fixed [here](https://github.com/B00merang-Project/Windows-10/issues/178)
