### ISSUE TITLE
Title bar of (at least) GNOME tweaks is invisible

### ISSUE THREAD

**Issue by Starwort** [B00merang-Project/Windows-10-Dark#23]
![image](https://user-images.githubusercontent.com/16487249/80402538-f17a3e80-88b5-11ea-8ac2-83a30509d47c.png)
See attached image

Theme version: 3.2
OS: Ubuntu 20.04

**Comment by Starwort** [comment]
![image](https://user-images.githubusercontent.com/16487249/80403714-f7711f00-88b7-11ea-886f-1a374f624d70.png)
Confirmation that this does not happen on older OS (Ubuntu 18.04, theme version 3.2)

**Comment by Elbullazul** [comment]
so it appears gnome has changed how titlebars work once more...

I'll see what I can do

**Comment by Starwort** [comment]
Also: Snap store (and presumably others) are in light theme, despite being win10-dark
![image](https://user-images.githubusercontent.com/16487249/80534499-3d50e480-8997-11ea-8750-f2314b591671.png)
But thanks!

Update: Also occurs with file dialogues
![image](https://user-images.githubusercontent.com/16487249/80537426-f74a4f80-899b-11ea-8780-b14deb492f26.png)

**Comment by Starwort** [comment]
Also text on notification dropdowns are nearly invisible until hover - it seems to be black in all cases

**Comment by Elbullazul** [comment]
can you upload a screenshot of the notif bug?

Software is now installed as a snap and snaps don't support custom themes (yet)

**Comment by Starwort** [comment]
![image](https://user-images.githubusercontent.com/16487249/80696040-b737b980-8ace-11ea-921a-052473acb91e.png)
(pre-hover)
![image](https://user-images.githubusercontent.com/16487249/80696066-c28ae500-8ace-11ea-8659-4f663ee02229.png)
(post-hover)
(sent with `notify-send "test" "test content"`)
Re: snap software - yaru dark successfully makes the applications dark, is there some flag you can set maybe? (Not meaning to be rude or anything, just doing my best to help you make the best theme you can!)
(Alternatively is there some flag *I* can set?)

**Comment by Elbullazul** [comment]
from what I gathered, a special package for snaps must be created. I'll investigate how to create that special package and update you when I have more info.

Will check that notification bug as soon as possible

**Comment by dominichayesferen** [comment]
@Elbullazul I contacted Popey about me creating a new Snap package for Feren OS's New GTK Theme once it's done, and he said this:
- Snap'd GTK Themes are all bundled into one snap
- Said snap only has 'popular themes'
- There aren't any plans to have people be able to make individual theme snaps (or at least he said something like that) for the Snap Store

Maybe your theme might be able to class as a popular enough theme, to Canonical, to be snap'd, but that's likely not the case, so you'll just have to wait for now until they, as they seem to be planning to do, improve how GTK themes are imported into Snaps.

Source for the actual conversation: https://t.me/bigdaddylinuxlive/181053

**Comment by Elbullazul** [comment]
I'm going to close this since it has been fixed. You should open a new issue another issue for snap packaging
