### ISSUE TITLE
⚠️ Borders in GTK3 application windows 🐞 

### ISSUE THREAD

**Issue by abraaorosa** [B00merang-Project/Windows-10-Dark#24]
Could someone please help me remove these white borders that are showing up in the GTK3 windows? In other applications it does not appear only in these.
Please, I tried all the ways but I couldn't remove it.

![image](https://user-images.githubusercontent.com/11440555/81509641-5d12d180-92e2-11ea-972a-3797842fec94.png)

I thank the attention 🙏

**Comment by Elbullazul** [comment]
is that unity?

**Comment by abraaorosa** [comment]
Hello guys. I managed to solve the problem by changing some expressions in the theme's GTK style sheet.

To resolve, go to:
`./usr/share/themes/Windows-10-dark/gtk-3.20/gtk.css`

And change values to:
`  .solid-csd decoration {
    margin: 1px;
    border-radius: 0px;
    background-color: #191919;
    box-shadow: none; }`

![image](https://user-images.githubusercontent.com/11440555/81529394-2619db80-9335-11ea-9485-61037cba77a5.png)

You can see that the GTK3 windows have no white borders.

Thank you!
