### ISSUE TITLE
More syntax errors easily fixed in most cases

### ISSUE THREAD

**Issue by frankzen** [B00merang-Project/Windows-10-Dark#3]
The "junk at end of value" errors are a simple double closing bracket thing.
The prelight:hover thing is also easily fixed.
The others I don't know enough about syntax to fix.
These are from a zip file downloaded today June 9th

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:2887:37: The :prelight pseudo-class is deprecated. Use :hover instead.

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:3503:49: Junk at end of value for background-image

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:3507:55: Junk at end of value for background-image

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:3511:61: Junk at end of value for background-image

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:3517:61: Junk at end of value for background-image

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:3522:61: Junk at end of value for background-image

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:24:64: Using one color stop with linear-gradient() is deprecated.

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:58:64: Using one color stop with linear-gradient() is deprecated.

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2527:75: Using one color stop with linear-gradient() is deprecated.

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2857:13: Expected a length

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2889:37: The :prelight pseudo-class is deprecated. Use :hover instead.

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3526:8: Junk at end of value for background-image

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4215:73: Using one color stop with linear-gradient() is deprecated.

(cinnamon-screensaver-main.py:3779): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4227:87: Using one color stop with linear-gradient() is deprecated.

**Comment by Elbullazul** [comment]
will check this weekend

**Comment by Elbullazul** [comment]
@frankzen we're moving out of the Adwaita codebase, mainly because of it's complexity and because I don't want to mess with compilation and pulling fixes from upstream.

we will be using a new method of creation and updating. But this kind of bugs should not happen anymore. 

Thanks for your feedback, and I will post back when v2.0.0 goes live

**Comment by Elbullazul** [comment]
Release 2.0 fixes this
