### ISSUE TITLE
Theme regression

### ISSUE THREAD

**Issue by leogx9r** [B00merang-Project/Windows-10-Dark#32]
Referencing commit 2b0bdcc4e5cf90817f187ee76253de3857d13ef4, this commit breaks the theme from being loaded due to a parsing error.

Instead of:

```css
    padding left: 3px;
    padding right: 3px;
```

It should be:

```css
    padding-left: 3px;
    padding-right: 3px;
```

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Project/Windows-10-Dark/pull/31

merged, thank you!
