### ISSUE TITLE
unable to see/scroll last line of package details in synaptic manager

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Dark#33]
shown working fine in mint y dark and flat remix darkest.

![2](https://user-images.githubusercontent.com/43943312/98428082-e35b7500-20c5-11eb-80f8-68fb7ab01781.gif)

**Comment by Elbullazul** [comment]
what distro and desktop are you using?

**Comment by Elbullazul** [comment]
and how do you change the theme for Synaptic? I'm not able to set a root theme (been a long time I messed with this program)

**Comment by Elbullazul** [comment]
figured it out.

doesn't happen on my side, just like acrylic. Probably an app bug? Or the window isn't maximized

**Comment by sidmint** [comment]
I used Linuxmint 19.3 xfce, window is maximised, yeah this is an app [synaptic package manager] bug instead I figured out by other cases and by moving the flexible bar for the package details area vertically [scroll bar doesn't get activated properly].
