### ISSUE TITLE
No theme for Marco in Windows 10 dark.

### ISSUE THREAD

**Issue by frankzen** [B00merang-Project/Windows-10-Dark#38]
I have installed the latest version of Windows 10 dark in my Mint Mate. When I run the appearance tab in control center it complains the theme will not look like it should because there is no theme for the window manger, which is Marco. Is there a solution to this ?

**Comment by Elbullazul** [comment]
it's an error with the theme's configuration file. You can manually change the window border theme by clicking 'customize' at the bottom of the window

**Comment by frankzen** [comment]
Yes I saw that. It doesn't happen with other themes however. Thanks

**Comment by Elbullazul** [comment]
the theme should be applied without any errors. I'll see what I can do to fix it

**Comment by frankzen** [comment]
**Great!!**

**Comment by Elbullazul** [comment]
It doesn't throw any errors on Ubuntu MATE 22.04. Are you still getting the alert?

**Comment by frankzen** [comment]
OK fixed! Thank you!
