### ISSUE TITLE
Windows-10-Dark-master-Mod

### ISSUE THREAD

**Issue by azjio** [B00merang-Project/Windows-10-Dark#39]
Author, check my theme edits
https://disk.yandex.ru/d/V3SFxBbCC9s38w

**Comment by Elbullazul** [comment]
can you list what changes you made?

**Comment by azjio** [comment]
Basically I changed the file "/Windows-10-Dark-master/gtk-3.20/gtk.css"
[screenshot](https://i.imgur.com/nphiKf1.png)
