### ISSUE TITLE
Strange coloration in Mate's caja

### ISSUE THREAD

**Issue by frankzen** [B00merang-Project/Windows-10-Dark#4]
Noticed this morning that the Windows-10-dark theme creates a strange acqua coloration of the background in Caja in Mate.
![screenshot from 2017-06-30 11-46-27](https://user-images.githubusercontent.com/717662/27743443-056a2f0e-5d8a-11e7-9124-90c05a52a062.png)

**Comment by Elbullazul** [comment]
@frankzen does a reboot fix it? caja has some weird bugs when switching between themes

**Comment by frankzen** [comment]
No multiple reboots. I suspect something to do with Murrine engine or themes. I have purged
murrine themes but no change

**Comment by frankzen** [comment]
No. I have rebooted multiple times. Strangely Cinnamon is not affected 
colors are

correct in that environment. I feel it has something to do with 
murrine-engine

because of the color (acqua).


I have removed the murrine themes from my computer but still have it.

**Comment by Elbullazul** [comment]
@frankzen this is odd. Can you post how it lookd with the Windows 10 Light theme and another theme?

**Comment by frankzen** [comment]
No need to. I just checked Menta and several other stock themes in Mate and they all show the same effect when Caja opens a directory, that acqua background. In the other themes of source the text is a different color, usually black. Never noticed this before.  Caja bug? or something weird? I will try several other things including removing the murrine-engine.

**Comment by frankzen** [comment]
Can't remove gtk-murrine-engine. It wants to pull out  3/4 of Mate. Oh well.

**Comment by Elbullazul** [comment]
@frankzen maybe this will help?

https://github.com/mate-desktop/caja/issues/81#issuecomment-172880792

**Comment by frankzen** [comment]
On 07/03/2017 10:42 AM, B00merang Project wrote:
>
> @frankzen <https://github.com/frankzen> maybe this will help?
>
> mate-desktop/caja#81 (comment) 
> <https://github.com/mate-desktop/caja/issues/81#issuecomment-172880792>
>
> —
>


   Wow. The dragging of a color onto the background works. Used
the color selector to pick black, dragged it onto the background
and it changed, and has stayed changed. That's great. Thanks for the
tip. I have no idea where the aqua color came from !!

**Comment by Elbullazul** [comment]
@frankzen maybe a setting that got corrupted or a bad update patch

glad this is fixed! Thanks for the feedback
