### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ThirstyThursten** [B00merang-Project/Windows-10-Dark#6]
Hello,

I don't have all the icons, meaning, my "start" button is still the stock mint icon..
I use Linux mint with xfce (Mint 18.3) 

It's for my work place, we fix up old systems for the elderly and less fortunate people and they can be scared off easily by the looks of Linux. Old systems so I'm trying with mint now because of the sys reqs.

But I would like to have the start button, I went through the transpack script which I used.

But teh set paths are non existant in my system, meaning, I don't have the folders in my home folder, (and yes I've looked for the hidden ones as well.)

Any help would wildely appreciated. =)

**Comment by Elbullazul** [comment]
The script installs the themes in /usr/share/themes, check over there, under Windows 10 Dark/extras

**Comment by Elbullazul** [comment]
The script installs the themes in /usr/share/themes, check over there, under Windows 10 Dark/extras

**Comment by Elbullazul** [comment]
The script installs the themes in /usr/share/themes, check over there,
under Windows 10 Dark/cinnamon got an image named menu.png
