### ISSUE TITLE
White corner pixel & background color suggestion

### ISSUE THREAD

**Issue by hitrikrtek** [B00merang-Project/Windows-10-Dark#9]
I am using your dark transformation theme with XFCE mostly and I've just updated to the latest version and noticed quite a few improvements but also one possible glitch:
Bottom left and bottom right pixel on windows have a white dot present:
![image](https://user-images.githubusercontent.com/34364792/52698610-1ebe2380-2f74-11e9-9655-e098129317d9.png)

The second part is more of a request, if you find it to make sense - current backgroud of dark theme, is a bit to black - it is matched with Windows 10 new Settings design but with 1809 we got dark explorer which looks something like this:
![image](https://user-images.githubusercontent.com/34364792/52698406-b3745180-2f73-11e9-8e84-de67db45cd8a.png)

I'd much more prefer a bit lighter dark for the whole theme, as I find myself swapping Appearance to something little brighter like Adwaita-Dark / Breeze-Dark / Arc-Dark:
![image](https://user-images.githubusercontent.com/34364792/52698877-bfacde80-2f74-11e9-98c0-700c446b198d.png)

Thank you very much for the great work you did on this transformation pack!

**Comment by Elbullazul** [comment]
fe2ee07737fa020f0b0a1766d74059bc9ebb23af fixes the Xfwm color issue and switches to a closer color match to Windows 10 dark mode

thank you for your feedback!
